"""add topic clusters and link classifications to clusters

Revision ID: 83f11aecbed3
Revises: 98a74d3f6cd2
Create Date: 2026-08-09 09:12:27.084351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f11aecbed3'
down_revision: Union[str, Sequence[str], None] = '98a74d3f6cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('cluster_name', sa.String(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comment_classifications', sa.Column('topic_albel_raw', sa.String(), nullable=True))
    op.add_column('comment_classifications', sa.Column('cluster_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'comment_classifications', 'topic_clusters', ['cluster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment_classifications', type_='foreignkey')
    op.drop_column('comment_classifications', 'cluster_id')
    op.drop_column('comment_classifications', 'topic_albel_raw')
    op.drop_table('topic_clusters')
    # ### end Alembic commands ###
